# Generated by Django 6.0.2 on 2026-04-27 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventpost_title_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(default='joe@joe.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='events.event'),
        ),
    ]
