# Generated by Django 6.0.2 on 2026-04-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_contact_email_alter_eventpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profile_photo',
            field=models.URLField(default='https://marg-stuff.sfo3.digitaloceanspaces.com/676161945_1311231290867219_2749971065757646726_n.jpg'),
            preserve_default=False,
        ),
    ]
