# Generated by Django 6.0.2 on 2026-04-27 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='music_url',
            field=models.URLField(default='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(7, 0)),
            preserve_default=False,
        ),
    ]
