# Generated by Django 6.0.2 on 2026-04-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_music_url_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='music_url',
            field=models.TextField(blank=True),
        ),
    ]
