# Generated by Django 6.0.2 on 2026-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_display_choice',
            field=models.CharField(default='tiled', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='background_url',
            field=models.URLField(blank=True),
        ),
    ]
