# Generated by Django 6.0.2 on 2026-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_background_display_choice_event_background_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_display_choice',
            field=models.CharField(choices=[('tiled', 'Tiled'), ('stretched', 'Stretched')], default='tiled', max_length=255),
        ),
    ]
