# Generated by Django 6.0.2 on 2026-04-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
