# Generated by Django 6.0.2 on 2026-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventcomment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='marquee_banner_text',
            field=models.TextField(blank=True),
        ),
    ]
