# Generated by Django 6.0.2 on 2026-04-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
