# Generated by Django 6.0.2 on 2026-04-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='relationship_status',
            field=models.CharField(blank=True),
        ),
    ]
