# Generated by Django 6.0.2 on 2026-04-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='profile_photo_url',
            field=models.URLField(default='blank'),
            preserve_default=False,
        ),
    ]
